name: Deploy to staging
'on':
  push:
    branches:
      - main
jobs:
  redeploy_everything:
    name: Deploying everything to staging
    runs-on: ubuntu-latest
    steps:
      - name: ssh into server and deploy
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          mkdir -p ~/.ssh 
          echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          ssh -i ~/ssh_key ubuntu@65.2.122.185 '
            # Source your profile to get the right PATH
            source ~/.profile
            source ~/.bashrc
            
            cd mono-repo-app/ && 
            git pull &&
            pnpm i &&
            pnpm run build &&
            /home/ubuntu/.nvm/versions/node/v23.0.0/bin/pm2 restart fe-server &&
            /home/ubuntu/.nvm/versions/node/v23.0.0/bin/pm2 restart http-server &&
            /home/ubuntu/.nvm/versions/node/v23.0.0/bin/pm2 restart ws-server
          '
