name: Deploy to staging
'on':
  push:
    branches:
      - main
jobs:
  redeploy_everything:
    name: Deploying everything to staging
    runs-on: ubuntu-latest
    steps:
      - name: ssh into server and deploy
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          mkdir -p ~/.ssh 
          echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          ssh -i ~/ssh_key ubuntu@13.201.166.216 '
            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
            
            if ! command -v pnpm &> /dev/null; then
              sudo npm install -g pnpm
            fi
            
            cd mono-repo-app/ && 
            git pull &&
            pnpm i &&
            pnpm run build &&
            pm2 restart fe-server &&
            pm2 restart http-server &&
            pm2 restart ws-server
          '